/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[48] = {44, 1, 0, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[84] = {80, 1, 0, 80, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[52] = {48, 1, 0, 48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47};

/* ackerman_model_cost_ext_cost_fun_jac:(i0[4],i1[44],i2[],i3[80])->(o0,o1[48]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=20.;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a2=(a0*a2);
  a3=arg[3]? arg[3][1] : 0;
  a4=arg[0]? arg[0][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a4=(a0*a4);
  a2=(a2+a4);
  a4=1.;
  a5=arg[3]? arg[3][2] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a5=(a5-a6);
  a6=cos(a5);
  a4=(a4-a6);
  a6=casadi_sq(a4);
  a6=(a0*a6);
  a2=(a2+a6);
  a6=2.0000000000000000e-08;
  a7=arg[3]? arg[3][4] : 0;
  a8=arg[1]? arg[1][0] : 0;
  a7=(a7-a8);
  a8=casadi_sq(a7);
  a8=(a6*a8);
  a2=(a2+a8);
  if (res[0]!=0) res[0][0]=a2;
  a7=(a7+a7);
  a6=(a6*a7);
  a6=(-a6);
  if (res[1]!=0) res[1][0]=a6;
  a6=0.;
  if (res[1]!=0) res[1][1]=a6;
  if (res[1]!=0) res[1][2]=a6;
  if (res[1]!=0) res[1][3]=a6;
  if (res[1]!=0) res[1][4]=a6;
  if (res[1]!=0) res[1][5]=a6;
  if (res[1]!=0) res[1][6]=a6;
  if (res[1]!=0) res[1][7]=a6;
  if (res[1]!=0) res[1][8]=a6;
  if (res[1]!=0) res[1][9]=a6;
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a6;
  if (res[1]!=0) res[1][12]=a6;
  if (res[1]!=0) res[1][13]=a6;
  if (res[1]!=0) res[1][14]=a6;
  if (res[1]!=0) res[1][15]=a6;
  if (res[1]!=0) res[1][16]=a6;
  if (res[1]!=0) res[1][17]=a6;
  if (res[1]!=0) res[1][18]=a6;
  if (res[1]!=0) res[1][19]=a6;
  if (res[1]!=0) res[1][20]=a6;
  if (res[1]!=0) res[1][21]=a6;
  if (res[1]!=0) res[1][22]=a6;
  if (res[1]!=0) res[1][23]=a6;
  if (res[1]!=0) res[1][24]=a6;
  if (res[1]!=0) res[1][25]=a6;
  if (res[1]!=0) res[1][26]=a6;
  if (res[1]!=0) res[1][27]=a6;
  if (res[1]!=0) res[1][28]=a6;
  if (res[1]!=0) res[1][29]=a6;
  if (res[1]!=0) res[1][30]=a6;
  if (res[1]!=0) res[1][31]=a6;
  if (res[1]!=0) res[1][32]=a6;
  if (res[1]!=0) res[1][33]=a6;
  if (res[1]!=0) res[1][34]=a6;
  if (res[1]!=0) res[1][35]=a6;
  if (res[1]!=0) res[1][36]=a6;
  if (res[1]!=0) res[1][37]=a6;
  if (res[1]!=0) res[1][38]=a6;
  if (res[1]!=0) res[1][39]=a6;
  if (res[1]!=0) res[1][40]=a6;
  if (res[1]!=0) res[1][41]=a6;
  if (res[1]!=0) res[1][42]=a6;
  if (res[1]!=0) res[1][43]=a6;
  a1=(a1+a1);
  a1=(a0*a1);
  a1=(-a1);
  if (res[1]!=0) res[1][44]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  a3=(-a3);
  if (res[1]!=0) res[1][45]=a3;
  a5=sin(a5);
  a4=(a4+a4);
  a0=(a0*a4);
  a5=(a5*a0);
  a5=(-a5);
  if (res[1]!=0) res[1][46]=a5;
  if (res[1]!=0) res[1][47]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
