/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[223] = {4, 44, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[48] = {44, 1, 0, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43};
static const casadi_int casadi_s4[84] = {80, 1, 0, 80, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79};

/* ackerman_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x44],i3[44],i4[80])->(o0[4],o1[4x4],o2[4x44]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=2.;
  a5=(a0/a4);
  a6=arg[3]? arg[3][1] : 0;
  a7=arg[3]? arg[3][2] : 0;
  a6=(a6+a7);
  a6=(a6/a4);
  a4=tan(a6);
  a7=(a5*a4);
  if (res[0]!=0) res[0][2]=a7;
  if (res[0]!=0) res[0][3]=a0;
  a7=sin(a1);
  a8=arg[1]? arg[1][2] : 0;
  a9=(a7*a8);
  a9=(a0*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][0]=a9;
  a9=cos(a1);
  a8=(a9*a8);
  a8=(a0*a8);
  if (res[1]!=0) res[1][1]=a8;
  a8=0.;
  if (res[1]!=0) res[1][2]=a8;
  if (res[1]!=0) res[1][3]=a8;
  a10=arg[1]? arg[1][6] : 0;
  a11=(a7*a10);
  a11=(a0*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][4]=a11;
  a10=(a9*a10);
  a10=(a0*a10);
  if (res[1]!=0) res[1][5]=a10;
  if (res[1]!=0) res[1][6]=a8;
  if (res[1]!=0) res[1][7]=a8;
  a10=arg[1]? arg[1][10] : 0;
  a11=(a7*a10);
  a11=(a0*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][8]=a11;
  a10=(a9*a10);
  a10=(a0*a10);
  if (res[1]!=0) res[1][9]=a10;
  if (res[1]!=0) res[1][10]=a8;
  if (res[1]!=0) res[1][11]=a8;
  a10=arg[1]? arg[1][14] : 0;
  a7=(a7*a10);
  a7=(a0*a7);
  a7=(-a7);
  if (res[1]!=0) res[1][12]=a7;
  a9=(a9*a10);
  a9=(a0*a9);
  if (res[1]!=0) res[1][13]=a9;
  if (res[1]!=0) res[1][14]=a8;
  if (res[1]!=0) res[1][15]=a8;
  a9=sin(a1);
  a10=arg[2]? arg[2][2] : 0;
  a7=(a9*a10);
  a7=(a0*a7);
  a2=(a2-a7);
  if (res[2]!=0) res[2][0]=a2;
  a1=cos(a1);
  a10=(a1*a10);
  a10=(a0*a10);
  a3=(a3+a10);
  if (res[2]!=0) res[2][1]=a3;
  a3=5.0000000000000000e-01;
  a4=(a3*a4);
  if (res[2]!=0) res[2][2]=a4;
  a4=1.;
  if (res[2]!=0) res[2][3]=a4;
  a4=arg[2]? arg[2][6] : 0;
  a10=(a9*a4);
  a10=(a0*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][4]=a10;
  a4=(a1*a4);
  a4=(a0*a4);
  if (res[2]!=0) res[2][5]=a4;
  a6=cos(a6);
  a6=casadi_sq(a6);
  a4=(a3/a6);
  a4=(a5*a4);
  if (res[2]!=0) res[2][6]=a4;
  if (res[2]!=0) res[2][7]=a8;
  a4=arg[2]? arg[2][10] : 0;
  a10=(a9*a4);
  a10=(a0*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][8]=a10;
  a4=(a1*a4);
  a4=(a0*a4);
  if (res[2]!=0) res[2][9]=a4;
  a3=(a3/a6);
  a5=(a5*a3);
  if (res[2]!=0) res[2][10]=a5;
  if (res[2]!=0) res[2][11]=a8;
  a5=arg[2]? arg[2][14] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][12]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][13]=a5;
  if (res[2]!=0) res[2][14]=a8;
  if (res[2]!=0) res[2][15]=a8;
  a5=arg[2]? arg[2][18] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][16]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][17]=a5;
  if (res[2]!=0) res[2][18]=a8;
  if (res[2]!=0) res[2][19]=a8;
  a5=arg[2]? arg[2][22] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][20]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][21]=a5;
  if (res[2]!=0) res[2][22]=a8;
  if (res[2]!=0) res[2][23]=a8;
  a5=arg[2]? arg[2][26] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][24]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][25]=a5;
  if (res[2]!=0) res[2][26]=a8;
  if (res[2]!=0) res[2][27]=a8;
  a5=arg[2]? arg[2][30] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][28]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][29]=a5;
  if (res[2]!=0) res[2][30]=a8;
  if (res[2]!=0) res[2][31]=a8;
  a5=arg[2]? arg[2][34] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][32]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][33]=a5;
  if (res[2]!=0) res[2][34]=a8;
  if (res[2]!=0) res[2][35]=a8;
  a5=arg[2]? arg[2][38] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][36]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][37]=a5;
  if (res[2]!=0) res[2][38]=a8;
  if (res[2]!=0) res[2][39]=a8;
  a5=arg[2]? arg[2][42] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][40]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][41]=a5;
  if (res[2]!=0) res[2][42]=a8;
  if (res[2]!=0) res[2][43]=a8;
  a5=arg[2]? arg[2][46] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][44]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][45]=a5;
  if (res[2]!=0) res[2][46]=a8;
  if (res[2]!=0) res[2][47]=a8;
  a5=arg[2]? arg[2][50] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][48]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][49]=a5;
  if (res[2]!=0) res[2][50]=a8;
  if (res[2]!=0) res[2][51]=a8;
  a5=arg[2]? arg[2][54] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][52]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][53]=a5;
  if (res[2]!=0) res[2][54]=a8;
  if (res[2]!=0) res[2][55]=a8;
  a5=arg[2]? arg[2][58] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][56]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][57]=a5;
  if (res[2]!=0) res[2][58]=a8;
  if (res[2]!=0) res[2][59]=a8;
  a5=arg[2]? arg[2][62] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][60]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][61]=a5;
  if (res[2]!=0) res[2][62]=a8;
  if (res[2]!=0) res[2][63]=a8;
  a5=arg[2]? arg[2][66] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][64]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][65]=a5;
  if (res[2]!=0) res[2][66]=a8;
  if (res[2]!=0) res[2][67]=a8;
  a5=arg[2]? arg[2][70] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][68]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][69]=a5;
  if (res[2]!=0) res[2][70]=a8;
  if (res[2]!=0) res[2][71]=a8;
  a5=arg[2]? arg[2][74] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][72]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][73]=a5;
  if (res[2]!=0) res[2][74]=a8;
  if (res[2]!=0) res[2][75]=a8;
  a5=arg[2]? arg[2][78] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][76]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][77]=a5;
  if (res[2]!=0) res[2][78]=a8;
  if (res[2]!=0) res[2][79]=a8;
  a5=arg[2]? arg[2][82] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][80]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][81]=a5;
  if (res[2]!=0) res[2][82]=a8;
  if (res[2]!=0) res[2][83]=a8;
  a5=arg[2]? arg[2][86] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][84]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][85]=a5;
  if (res[2]!=0) res[2][86]=a8;
  if (res[2]!=0) res[2][87]=a8;
  a5=arg[2]? arg[2][90] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][88]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][89]=a5;
  if (res[2]!=0) res[2][90]=a8;
  if (res[2]!=0) res[2][91]=a8;
  a5=arg[2]? arg[2][94] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][92]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][93]=a5;
  if (res[2]!=0) res[2][94]=a8;
  if (res[2]!=0) res[2][95]=a8;
  a5=arg[2]? arg[2][98] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][96]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][97]=a5;
  if (res[2]!=0) res[2][98]=a8;
  if (res[2]!=0) res[2][99]=a8;
  a5=arg[2]? arg[2][102] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][100]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][101]=a5;
  if (res[2]!=0) res[2][102]=a8;
  if (res[2]!=0) res[2][103]=a8;
  a5=arg[2]? arg[2][106] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][104]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][105]=a5;
  if (res[2]!=0) res[2][106]=a8;
  if (res[2]!=0) res[2][107]=a8;
  a5=arg[2]? arg[2][110] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][108]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][109]=a5;
  if (res[2]!=0) res[2][110]=a8;
  if (res[2]!=0) res[2][111]=a8;
  a5=arg[2]? arg[2][114] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][112]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][113]=a5;
  if (res[2]!=0) res[2][114]=a8;
  if (res[2]!=0) res[2][115]=a8;
  a5=arg[2]? arg[2][118] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][116]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][117]=a5;
  if (res[2]!=0) res[2][118]=a8;
  if (res[2]!=0) res[2][119]=a8;
  a5=arg[2]? arg[2][122] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][120]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][121]=a5;
  if (res[2]!=0) res[2][122]=a8;
  if (res[2]!=0) res[2][123]=a8;
  a5=arg[2]? arg[2][126] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][124]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][125]=a5;
  if (res[2]!=0) res[2][126]=a8;
  if (res[2]!=0) res[2][127]=a8;
  a5=arg[2]? arg[2][130] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][128]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][129]=a5;
  if (res[2]!=0) res[2][130]=a8;
  if (res[2]!=0) res[2][131]=a8;
  a5=arg[2]? arg[2][134] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][132]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][133]=a5;
  if (res[2]!=0) res[2][134]=a8;
  if (res[2]!=0) res[2][135]=a8;
  a5=arg[2]? arg[2][138] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][136]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][137]=a5;
  if (res[2]!=0) res[2][138]=a8;
  if (res[2]!=0) res[2][139]=a8;
  a5=arg[2]? arg[2][142] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][140]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][141]=a5;
  if (res[2]!=0) res[2][142]=a8;
  if (res[2]!=0) res[2][143]=a8;
  a5=arg[2]? arg[2][146] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][144]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][145]=a5;
  if (res[2]!=0) res[2][146]=a8;
  if (res[2]!=0) res[2][147]=a8;
  a5=arg[2]? arg[2][150] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][148]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][149]=a5;
  if (res[2]!=0) res[2][150]=a8;
  if (res[2]!=0) res[2][151]=a8;
  a5=arg[2]? arg[2][154] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][152]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][153]=a5;
  if (res[2]!=0) res[2][154]=a8;
  if (res[2]!=0) res[2][155]=a8;
  a5=arg[2]? arg[2][158] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][156]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][157]=a5;
  if (res[2]!=0) res[2][158]=a8;
  if (res[2]!=0) res[2][159]=a8;
  a5=arg[2]? arg[2][162] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][160]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][161]=a5;
  if (res[2]!=0) res[2][162]=a8;
  if (res[2]!=0) res[2][163]=a8;
  a5=arg[2]? arg[2][166] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][164]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][165]=a5;
  if (res[2]!=0) res[2][166]=a8;
  if (res[2]!=0) res[2][167]=a8;
  a5=arg[2]? arg[2][170] : 0;
  a3=(a9*a5);
  a3=(a0*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][168]=a3;
  a5=(a1*a5);
  a5=(a0*a5);
  if (res[2]!=0) res[2][169]=a5;
  if (res[2]!=0) res[2][170]=a8;
  if (res[2]!=0) res[2][171]=a8;
  a5=arg[2]? arg[2][174] : 0;
  a9=(a9*a5);
  a9=(a0*a9);
  a9=(-a9);
  if (res[2]!=0) res[2][172]=a9;
  a1=(a1*a5);
  a0=(a0*a1);
  if (res[2]!=0) res[2][173]=a0;
  if (res[2]!=0) res[2][174]=a8;
  if (res[2]!=0) res[2][175]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
