/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int cbf_solver(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int cbf_solver_alloc_mem(void);
extern "C" int cbf_solver_init_mem(int mem);
extern "C" void cbf_solver_free_mem(int mem);
extern "C" int cbf_solver_checkout(void);
extern "C" void cbf_solver_release(int mem);
extern "C" void cbf_solver_incref(void);
extern "C" void cbf_solver_decref(void);
extern "C" casadi_int cbf_solver_n_in(void);
extern "C" casadi_int cbf_solver_n_out(void);
extern "C" casadi_real cbf_solver_default_in(casadi_int i);
extern "C" const char* cbf_solver_name_in(casadi_int i);
extern "C" const char* cbf_solver_name_out(casadi_int i);
extern "C" const casadi_int* cbf_solver_sparsity_in(casadi_int i);
extern "C" const casadi_int* cbf_solver_sparsity_out(casadi_int i);
extern "C" int cbf_solver_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int cbf_solver_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define cbf_solver_SZ_ARG 12
#define cbf_solver_SZ_RES 10
#define cbf_solver_SZ_IW 0
#define cbf_solver_SZ_W 111
