/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[42] = {38, 1, 0, 38, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37};
static const casadi_int casadi_s4[18] = {8, 5, 0, 2, 4, 6, 8, 10, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4};
static const casadi_int casadi_s5[3] = {5, 0, 0};

/* ackerman_model_constr_h_fun_jac_uxt_zt:(i0[5],i1[3],i2[],i3[38])->(o0[5],o1[8x5,10nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][12] : 0;
  a1=0.;
  a2=(a0==a1);
  a3=arg[3]? arg[3][13] : 0;
  a4=(a3==a1);
  a2=(a2&&a4);
  a4=10.;
  a5=arg[3]? arg[3][8] : 0;
  a6=arg[0]? arg[0][0] : 0;
  a5=(a5-a6);
  a7=casadi_sq(a5);
  a8=arg[3]? arg[3][9] : 0;
  a9=arg[0]? arg[0][1] : 0;
  a8=(a8-a9);
  a10=casadi_sq(a8);
  a7=(a7+a10);
  a10=sqrt(a7);
  a10=(a4<=a10);
  a2=(a2||a10);
  a2=(!a2);
  a10=2.;
  a0=(a0/a10);
  a0=casadi_sq(a0);
  a3=(a3/a10);
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=sqrt(a0);
  a3=2.5059928172283334e+00;
  a0=(a0+a3);
  a11=5.0000000000000000e-01;
  a0=(a0+a11);
  a0=casadi_sq(a0);
  a7=(a7-a0);
  a7=(a2?a7:0);
  a7=(-a7);
  if (res[0]!=0) res[0][0]=a7;
  a7=arg[3]? arg[3][18] : 0;
  a0=(a7==a1);
  a12=arg[3]? arg[3][19] : 0;
  a13=(a12==a1);
  a0=(a0&&a13);
  a13=arg[3]? arg[3][14] : 0;
  a13=(a13-a6);
  a14=casadi_sq(a13);
  a15=arg[3]? arg[3][15] : 0;
  a15=(a15-a9);
  a16=casadi_sq(a15);
  a14=(a14+a16);
  a16=sqrt(a14);
  a16=(a4<=a16);
  a0=(a0||a16);
  a0=(!a0);
  a7=(a7/a10);
  a7=casadi_sq(a7);
  a12=(a12/a10);
  a12=casadi_sq(a12);
  a7=(a7+a12);
  a7=sqrt(a7);
  a7=(a7+a3);
  a7=(a7+a11);
  a7=casadi_sq(a7);
  a14=(a14-a7);
  a14=(a0?a14:0);
  a14=(-a14);
  if (res[0]!=0) res[0][1]=a14;
  a14=arg[3]? arg[3][24] : 0;
  a7=(a14==a1);
  a12=arg[3]? arg[3][25] : 0;
  a16=(a12==a1);
  a7=(a7&&a16);
  a16=arg[3]? arg[3][20] : 0;
  a16=(a16-a6);
  a17=casadi_sq(a16);
  a18=arg[3]? arg[3][21] : 0;
  a18=(a18-a9);
  a19=casadi_sq(a18);
  a17=(a17+a19);
  a19=sqrt(a17);
  a19=(a4<=a19);
  a7=(a7||a19);
  a7=(!a7);
  a14=(a14/a10);
  a14=casadi_sq(a14);
  a12=(a12/a10);
  a12=casadi_sq(a12);
  a14=(a14+a12);
  a14=sqrt(a14);
  a14=(a14+a3);
  a14=(a14+a11);
  a14=casadi_sq(a14);
  a17=(a17-a14);
  a17=(a7?a17:0);
  a17=(-a17);
  if (res[0]!=0) res[0][2]=a17;
  a17=arg[3]? arg[3][30] : 0;
  a14=(a17==a1);
  a12=arg[3]? arg[3][31] : 0;
  a19=(a12==a1);
  a14=(a14&&a19);
  a19=arg[3]? arg[3][26] : 0;
  a19=(a19-a6);
  a20=casadi_sq(a19);
  a21=arg[3]? arg[3][27] : 0;
  a21=(a21-a9);
  a22=casadi_sq(a21);
  a20=(a20+a22);
  a22=sqrt(a20);
  a22=(a4<=a22);
  a14=(a14||a22);
  a14=(!a14);
  a17=(a17/a10);
  a17=casadi_sq(a17);
  a12=(a12/a10);
  a12=casadi_sq(a12);
  a17=(a17+a12);
  a17=sqrt(a17);
  a17=(a17+a3);
  a17=(a17+a11);
  a17=casadi_sq(a17);
  a20=(a20-a17);
  a20=(a14?a20:0);
  a20=(-a20);
  if (res[0]!=0) res[0][3]=a20;
  a20=arg[3]? arg[3][36] : 0;
  a17=(a20==a1);
  a12=arg[3]? arg[3][37] : 0;
  a1=(a12==a1);
  a17=(a17&&a1);
  a1=arg[3]? arg[3][32] : 0;
  a1=(a1-a6);
  a6=casadi_sq(a1);
  a22=arg[3]? arg[3][33] : 0;
  a22=(a22-a9);
  a9=casadi_sq(a22);
  a6=(a6+a9);
  a9=sqrt(a6);
  a4=(a4<=a9);
  a17=(a17||a4);
  a17=(!a17);
  a20=(a20/a10);
  a20=casadi_sq(a20);
  a12=(a12/a10);
  a12=casadi_sq(a12);
  a20=(a20+a12);
  a20=sqrt(a20);
  a20=(a20+a3);
  a20=(a20+a11);
  a20=casadi_sq(a20);
  a6=(a6-a20);
  a6=(a17?a6:0);
  a6=(-a6);
  if (res[0]!=0) res[0][4]=a6;
  a5=(a5+a5);
  a5=(a2?a5:0);
  if (res[1]!=0) res[1][0]=a5;
  a8=(a8+a8);
  a2=(a2?a8:0);
  if (res[1]!=0) res[1][1]=a2;
  a13=(a13+a13);
  a13=(a0?a13:0);
  if (res[1]!=0) res[1][2]=a13;
  a15=(a15+a15);
  a0=(a0?a15:0);
  if (res[1]!=0) res[1][3]=a0;
  a16=(a16+a16);
  a16=(a7?a16:0);
  if (res[1]!=0) res[1][4]=a16;
  a18=(a18+a18);
  a7=(a7?a18:0);
  if (res[1]!=0) res[1][5]=a7;
  a19=(a19+a19);
  a19=(a14?a19:0);
  if (res[1]!=0) res[1][6]=a19;
  a21=(a21+a21);
  a14=(a14?a21:0);
  if (res[1]!=0) res[1][7]=a14;
  a1=(a1+a1);
  a1=(a17?a1:0);
  if (res[1]!=0) res[1][8]=a1;
  a22=(a22+a22);
  a17=(a17?a22:0);
  if (res[1]!=0) res[1][9]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
