/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};

/* ackerman_model_constr_h_fun:(i0[4],i1[3],i2[],i3[7])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.8007260979305963e-02;
  if (res[0]!=0) res[0][0]=a0;
  a0=3.6965343844299718e-02;
  if (res[0]!=0) res[0][1]=a0;
  a0=1.8007260979302400e-02;
  if (res[0]!=0) res[0][2]=a0;
  a0=3.6965343844299808e-02;
  if (res[0]!=0) res[0][3]=a0;
  a0=2.2302273640612930e-14;
  if (res[0]!=0) res[0][4]=a0;
  a1=5.1829584712450195e-14;
  if (res[0]!=0) res[0][5]=a1;
  a2=2.5558253370310121e-14;
  if (res[0]!=0) res[0][6]=a2;
  a3=5.3111208356824353e-14;
  if (res[0]!=0) res[0][7]=a3;
  a4=8.0352391407245705e-15;
  a5=arg[0]? arg[0][0] : 0;
  a6=2.;
  a7=(a5+a6);
  a8=2.2799999999999998e+00;
  a9=(a7+a8);
  a9=(a5-a9);
  a9=(a2*a9);
  a8=(a8-a7);
  a5=(a5+a8);
  a5=(a0*a5);
  a8=arg[0]? arg[0][1] : 0;
  a7=1.0400000000000000e+00;
  a6=(a8+a6);
  a10=(a7-a6);
  a10=(a8+a10);
  a10=(a1*a10);
  a5=(a5+a10);
  a9=(a9-a5);
  a6=(a6+a7);
  a8=(a8-a6);
  a8=(a3*a8);
  a9=(a9+a8);
  a4=(a4+a9);
  if (res[0]!=0) res[0][8]=a4;
  a4=-3.5631220196563618e-15;
  a9=arg[0]? arg[0][3] : 0;
  a8=sin(a9);
  a6=(a1*a8);
  a7=cos(a9);
  a5=(a0*a7);
  a6=(a6-a5);
  a7=(a2*a7);
  a6=(a6+a7);
  a8=(a3*a8);
  a6=(a6-a8);
  a4=(a4+a6);
  if (res[0]!=0) res[0][9]=a4;
  a4=9.0205620750793969e-17;
  a6=sin(a9);
  a2=(a2*a6);
  a0=(a0*a6);
  a9=cos(a9);
  a1=(a1*a9);
  a0=(a0+a1);
  a2=(a2-a0);
  a3=(a3*a9);
  a2=(a2+a3);
  a4=(a4+a2);
  if (res[0]!=0) res[0][10]=a4;
  a4=3.2559797296971908e-15;
  if (res[0]!=0) res[0][11]=a4;
  a4=1.2816236443741578e-15;
  if (res[0]!=0) res[0][12]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
