/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[48] = {44, 1, 0, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[84] = {80, 1, 0, 80, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};

/* ackerman_model_constr_h_fun:(i0[4],i1[44],i2[],i3[80])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][54] : 0;
  a1=0.;
  a2=(a0==a1);
  a2=(!a2);
  a3=arg[1]? arg[1][3] : 0;
  a4=(a2?a3:0);
  if (res[0]!=0) res[0][0]=a4;
  a4=arg[1]? arg[1][4] : 0;
  a5=(a2?a4:0);
  if (res[0]!=0) res[0][1]=a5;
  a5=arg[1]? arg[1][5] : 0;
  a6=(a2?a5:0);
  if (res[0]!=0) res[0][2]=a6;
  a6=arg[1]? arg[1][6] : 0;
  a7=(a2?a6:0);
  if (res[0]!=0) res[0][3]=a7;
  a1=(a0==a1);
  a1=(!a1);
  a7=arg[1]? arg[1][7] : 0;
  a8=(a1?a7:0);
  if (res[0]!=0) res[0][4]=a8;
  a8=arg[1]? arg[1][8] : 0;
  a9=(a1?a8:0);
  if (res[0]!=0) res[0][5]=a9;
  a9=arg[1]? arg[1][9] : 0;
  a10=(a1?a9:0);
  if (res[0]!=0) res[0][6]=a10;
  a10=arg[1]? arg[1][10] : 0;
  a11=(a1?a10:0);
  if (res[0]!=0) res[0][7]=a11;
  a11=1.;
  a12=arg[0]? arg[0][2] : 0;
  a13=5.0000000000000000e-01;
  a14=1.6666666666666666e-01;
  a15=arg[1]? arg[1][0] : 0;
  a16=2.;
  a17=(a15/a16);
  a18=arg[1]? arg[1][1] : 0;
  a19=arg[1]? arg[1][2] : 0;
  a20=(a18+a19);
  a20=(a20/a16);
  a20=tan(a20);
  a17=(a17*a20);
  a20=(a15/a16);
  a21=(a18+a19);
  a21=(a21/a16);
  a21=tan(a21);
  a20=(a20*a21);
  a21=(a16*a20);
  a21=(a17+a21);
  a22=(a15/a16);
  a23=(a18+a19);
  a23=(a23/a16);
  a23=tan(a23);
  a22=(a22*a23);
  a23=(a16*a22);
  a21=(a21+a23);
  a23=(a15/a16);
  a18=(a18+a19);
  a18=(a18/a16);
  a18=tan(a18);
  a23=(a23*a18);
  a21=(a21+a23);
  a21=(a14*a21);
  a21=(a13*a21);
  a21=(a12+a21);
  a23=cos(a21);
  a18=arg[0]? arg[0][0] : 0;
  a19=cos(a12);
  a19=(a15*a19);
  a24=2.5000000000000000e-01;
  a17=(a24*a17);
  a17=(a12+a17);
  a25=cos(a17);
  a25=(a15*a25);
  a25=(a16*a25);
  a19=(a19+a25);
  a24=(a24*a20);
  a24=(a12+a24);
  a20=cos(a24);
  a20=(a15*a20);
  a20=(a16*a20);
  a19=(a19+a20);
  a22=(a13*a22);
  a22=(a12+a22);
  a20=cos(a22);
  a20=(a15*a20);
  a19=(a19+a20);
  a19=(a14*a19);
  a19=(a13*a19);
  a18=(a18+a19);
  a19=(a23*a18);
  a20=sin(a21);
  a25=arg[0]? arg[0][1] : 0;
  a12=sin(a12);
  a12=(a15*a12);
  a17=sin(a17);
  a17=(a15*a17);
  a17=(a16*a17);
  a12=(a12+a17);
  a24=sin(a24);
  a24=(a15*a24);
  a24=(a16*a24);
  a12=(a12+a24);
  a22=sin(a22);
  a15=(a15*a22);
  a12=(a12+a15);
  a14=(a14*a12);
  a13=(a13*a14);
  a25=(a25+a13);
  a13=(a20*a25);
  a19=(a19+a13);
  a19=(a11-a19);
  a19=(a19*a3);
  a13=sin(a21);
  a14=(a13*a18);
  a21=cos(a21);
  a12=(a21*a25);
  a14=(a14-a12);
  a14=(a14+a11);
  a14=(a14*a4);
  a19=(a19+a14);
  a14=(a23*a18);
  a12=(a20*a25);
  a14=(a14+a12);
  a14=(a14+a11);
  a14=(a14*a5);
  a19=(a19+a14);
  a25=(a21*a25);
  a18=(a13*a18);
  a25=(a25-a18);
  a25=(a25+a11);
  a25=(a25*a6);
  a19=(a19+a25);
  a19=(a2?a19:0);
  a25=arg[3]? arg[3][52] : 0;
  a11=(a25/a16);
  a18=arg[3]? arg[3][51] : 0;
  a14=cos(a18);
  a12=arg[3]? arg[3][49] : 0;
  a15=(a14*a12);
  a22=sin(a18);
  a24=arg[3]? arg[3][50] : 0;
  a17=(a22*a24);
  a15=(a15+a17);
  a11=(a11-a15);
  a11=(a11*a7);
  a15=sin(a18);
  a17=(a15*a12);
  a18=cos(a18);
  a26=(a18*a24);
  a17=(a17-a26);
  a26=arg[3]? arg[3][53] : 0;
  a27=(a26/a16);
  a17=(a17+a27);
  a17=(a17*a8);
  a11=(a11+a17);
  a17=(a14*a12);
  a27=(a22*a24);
  a17=(a17+a27);
  a25=(a25/a16);
  a17=(a17+a25);
  a17=(a17*a9);
  a11=(a11+a17);
  a24=(a18*a24);
  a12=(a15*a12);
  a24=(a24-a12);
  a26=(a26/a16);
  a24=(a24+a26);
  a24=(a24*a10);
  a11=(a11+a24);
  a11=(a1?a11:0);
  a19=(a19+a11);
  a11=arg[1]? arg[1][43] : 0;
  a24=arg[3]? arg[3][79] : 0;
  a24=(a11*a24);
  a24=(a24*a0);
  a19=(a19+a24);
  a19=(-a19);
  if (res[0]!=0) res[0][8]=a19;
  a19=(a13*a4);
  a24=(a23*a3);
  a19=(a19-a24);
  a23=(a23*a5);
  a19=(a19+a23);
  a13=(a13*a6);
  a19=(a19-a13);
  a19=(a2?a19:0);
  a13=(a15*a8);
  a23=(a14*a7);
  a13=(a13-a23);
  a23=(a14*a9);
  a13=(a13+a23);
  a23=(a15*a10);
  a13=(a13-a23);
  a13=(a1?a13:0);
  a19=(a19+a13);
  if (res[0]!=0) res[0][9]=a19;
  a5=(a20*a5);
  a20=(a20*a3);
  a4=(a21*a4);
  a20=(a20+a4);
  a5=(a5-a20);
  a21=(a21*a6);
  a5=(a5+a21);
  a2=(a2?a5:0);
  a5=(a22*a9);
  a21=(a22*a7);
  a6=(a18*a8);
  a21=(a21+a6);
  a5=(a5-a21);
  a21=(a18*a10);
  a5=(a5+a21);
  a5=(a1?a5:0);
  a2=(a2+a5);
  if (res[0]!=0) res[0][10]=a2;
  a2=(a15*a8);
  a5=(a14*a7);
  a2=(a2-a5);
  a14=(a14*a9);
  a2=(a2+a14);
  a15=(a15*a10);
  a2=(a2-a15);
  a2=casadi_sq(a2);
  a9=(a22*a9);
  a22=(a22*a7);
  a8=(a18*a8);
  a22=(a22+a8);
  a9=(a9-a22);
  a18=(a18*a10);
  a9=(a9+a18);
  a9=casadi_sq(a9);
  a2=(a2+a9);
  a2=(a1?a2:0);
  a1=(a1?a2:0);
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
