/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ackerman_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[18] = {4, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* ackerman_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x3],i3[3],i4[7])->(o0[4],o1[4x4],o2[4x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=1.2800000000000000e+00;
  a3=arg[3]? arg[3][1] : 0;
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3+a4);
  a4=2.;
  a3=(a3/a4);
  a4=tan(a3);
  a4=(a2*a4);
  a5=2.5600000000000001e+00;
  a6=atan2(a4,a5);
  a7=(a1+a6);
  a8=cos(a7);
  a9=(a0*a8);
  if (res[0]!=0) res[0][0]=a9;
  a1=(a1+a6);
  a9=sin(a1);
  a10=(a0*a9);
  if (res[0]!=0) res[0][1]=a10;
  a10=(a0/a2);
  a11=sin(a6);
  a12=(a10*a11);
  if (res[0]!=0) res[0][2]=a12;
  a12=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a12;
  a12=arg[1]? arg[1][3] : 0;
  a13=(a8*a12);
  a14=sin(a7);
  a15=arg[1]? arg[1][2] : 0;
  a16=(a14*a15);
  a16=(a0*a16);
  a13=(a13-a16);
  if (res[1]!=0) res[1][0]=a13;
  a13=(a9*a12);
  a16=cos(a1);
  a15=(a16*a15);
  a15=(a0*a15);
  a13=(a13+a15);
  if (res[1]!=0) res[1][1]=a13;
  a13=7.8125000000000000e-01;
  a12=(a13*a12);
  a12=(a11*a12);
  if (res[1]!=0) res[1][2]=a12;
  a12=0.;
  if (res[1]!=0) res[1][3]=a12;
  a15=arg[1]? arg[1][7] : 0;
  a17=(a8*a15);
  a18=arg[1]? arg[1][6] : 0;
  a19=(a14*a18);
  a19=(a0*a19);
  a17=(a17-a19);
  if (res[1]!=0) res[1][4]=a17;
  a17=(a9*a15);
  a18=(a16*a18);
  a18=(a0*a18);
  a17=(a17+a18);
  if (res[1]!=0) res[1][5]=a17;
  a15=(a13*a15);
  a15=(a11*a15);
  if (res[1]!=0) res[1][6]=a15;
  if (res[1]!=0) res[1][7]=a12;
  a15=arg[1]? arg[1][11] : 0;
  a17=(a8*a15);
  a18=arg[1]? arg[1][10] : 0;
  a19=(a14*a18);
  a19=(a0*a19);
  a17=(a17-a19);
  if (res[1]!=0) res[1][8]=a17;
  a17=(a9*a15);
  a18=(a16*a18);
  a18=(a0*a18);
  a17=(a17+a18);
  if (res[1]!=0) res[1][9]=a17;
  a15=(a13*a15);
  a15=(a11*a15);
  if (res[1]!=0) res[1][10]=a15;
  if (res[1]!=0) res[1][11]=a12;
  a15=arg[1]? arg[1][15] : 0;
  a17=(a8*a15);
  a18=arg[1]? arg[1][14] : 0;
  a14=(a14*a18);
  a14=(a0*a14);
  a17=(a17-a14);
  if (res[1]!=0) res[1][12]=a17;
  a17=(a9*a15);
  a16=(a16*a18);
  a16=(a0*a16);
  a17=(a17+a16);
  if (res[1]!=0) res[1][13]=a17;
  a15=(a13*a15);
  a15=(a11*a15);
  if (res[1]!=0) res[1][14]=a15;
  if (res[1]!=0) res[1][15]=a12;
  a15=arg[2]? arg[2][3] : 0;
  a17=(a8*a15);
  a16=sin(a7);
  a18=arg[2]? arg[2][2] : 0;
  a14=(a16*a18);
  a14=(a0*a14);
  a17=(a17-a14);
  if (res[2]!=0) res[2][0]=a17;
  a17=(a9*a15);
  a14=cos(a1);
  a18=(a14*a18);
  a18=(a0*a18);
  a17=(a17+a18);
  if (res[2]!=0) res[2][1]=a17;
  a15=(a13*a15);
  a15=(a11*a15);
  if (res[2]!=0) res[2][2]=a15;
  a15=1.;
  if (res[2]!=0) res[2][3]=a15;
  a15=arg[2]? arg[2][7] : 0;
  a17=(a8*a15);
  a18=arg[2]? arg[2][6] : 0;
  a19=(a16*a18);
  a19=(a0*a19);
  a17=(a17-a19);
  a7=sin(a7);
  a4=casadi_sq(a4);
  a19=6.5536000000000003e+00;
  a4=(a4+a19);
  a5=(a5/a4);
  a4=5.0000000000000000e-01;
  a3=cos(a3);
  a3=casadi_sq(a3);
  a19=(a4/a3);
  a19=(a2*a19);
  a19=(a5*a19);
  a20=(a7*a19);
  a20=(a0*a20);
  a17=(a17-a20);
  if (res[2]!=0) res[2][4]=a17;
  a1=cos(a1);
  a17=(a1*a19);
  a17=(a0*a17);
  a20=(a9*a15);
  a18=(a14*a18);
  a18=(a0*a18);
  a20=(a20+a18);
  a17=(a17+a20);
  if (res[2]!=0) res[2][5]=a17;
  a6=cos(a6);
  a19=(a6*a19);
  a19=(a10*a19);
  a15=(a13*a15);
  a15=(a11*a15);
  a19=(a19+a15);
  if (res[2]!=0) res[2][6]=a19;
  if (res[2]!=0) res[2][7]=a12;
  a19=arg[2]? arg[2][11] : 0;
  a8=(a8*a19);
  a15=arg[2]? arg[2][10] : 0;
  a16=(a16*a15);
  a16=(a0*a16);
  a8=(a8-a16);
  a4=(a4/a3);
  a2=(a2*a4);
  a5=(a5*a2);
  a7=(a7*a5);
  a7=(a0*a7);
  a8=(a8-a7);
  if (res[2]!=0) res[2][8]=a8;
  a1=(a1*a5);
  a1=(a0*a1);
  a9=(a9*a19);
  a14=(a14*a15);
  a0=(a0*a14);
  a9=(a9+a0);
  a1=(a1+a9);
  if (res[2]!=0) res[2][9]=a1;
  a6=(a6*a5);
  a10=(a10*a6);
  a13=(a13*a19);
  a11=(a11*a13);
  a10=(a10+a11);
  if (res[2]!=0) res[2][10]=a10;
  if (res[2]!=0) res[2][11]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ackerman_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ackerman_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ackerman_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ackerman_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ackerman_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ackerman_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
